language: ruby

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1

# install fresh version of bundler, since older ones blow up trying to install
# rspec
before_install:
  gem install bundler
